FROM apache/airflow:2.9.2-python3.12

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential libpq-dev \
    && rm -rf /var/lib/apt/lists/*

USER airflow
ENV PATH=/opt/airflow/venv/bin:$PATH

COPY requirements.txt /tmp/requirements.txt
RUN /opt/airflow/venv/bin/pip install --no-cache-dir -r /tmp/requirements.txt

COPY --chown=airflow:root src/ /opt/airflow/src/
COPY --chown=airflow:root dags/ /opt/airflow/dags/

ENV PYTHONPATH=/opt/airflow
